#!/usr/bin/env sh
mono sim.exe \
-N 8 \
-output ./rbla.dat \
-mem2.channel_max 1 \
-mem2.rank_max 1 \
-mem.channel_max 1 \
-mem.rank_max 1 \
-mem2.map_type ROW_COL_RANK_BANK_CHAN \
-mem.map_type ROW_COL_RANK_BANK_CHAN \
-sched.is_omniscient true \
-proc.wb true \
-proc.cache true \
-proc.cache_replacement_policy DRAMTrueLRU \
-proc.cache_insertion_policy RBLA \
-proc.cache_write_policy WriteBack \
-sched.sched_algo FRFCFS \
-mctrl.page_randomize true \
-sim_type INST \
-sim_inst_max 5000000 \
-warmup_inst_max 5000000 \
-TraceDirs ./FilteredTrace \
-traces cpu2006-astar.gz cpu2006-astar.gz cpu2006-astar.gz cpu2006-astar.gz cpu2006-astar.gz cpu2006-astar.gz cpu2006-astar.gz cpu2006-astar.gz 
